# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1️⃣ Checkout repository
    - uses: actions/checkout@v3
    
    # 2️⃣ Setup Flutter
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    # 3️⃣ Build Flutter Web
    - name: Build Web
      run: flutter build web --base-href "/my_flutter_app/"
    
    # 4️⃣ Deploy ke GitHub Pages menggunakan PAT
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        # Ganti ini dengan Secret PAT yang kamu buat sendiri
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./build/web
        # Optional: jika ingin force push
        force_orphan: true
